config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  resources :games
  resources :miniatures
  root to: "home#index", as: 'home'
  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/collection/:game', to: 'miniatures#by_user_for_game', as: 'user_miniatures'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :miniatures
end

app/models/miniature.rb
class Miniature < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :miniatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dashboard
    @games = Game.all
  end
end

app/controllers/miniatures_controller.rb
class MiniaturesController < ApplicationController
  before_action :set_miniature, only: [:show, :edit, :update, :destroy]

  # GET /miniatures
  # GET /miniatures.json
  def index
    @miniatures = Miniature.all
  end

  # GET /miniatures/1
  # GET /miniatures/1.json
  def show
  end

  # GET /miniatures/new
  def new
    @miniature = Miniature.new
  end

  # GET /miniatures/1/edit
  def edit
  end

  # POST /miniatures
  # POST /miniatures.json
  def create
    @miniature = Miniature.new(miniature_params)

    respond_to do |format|
      if @miniature.save
        format.html { redirect_to @miniature, notice: 'Miniature was successfully created.' }
        format.json { render :show, status: :created, location: @miniature }
      else
        format.html { render :new }
        format.json { render json: @miniature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miniatures/1
  # PATCH/PUT /miniatures/1.json
  def update
    respond_to do |format|
      if @miniature.update(miniature_params)
        format.html { redirect_to @miniature, notice: 'Miniature was successfully updated.' }
        format.json { render :show, status: :ok, location: @miniature }
      else
        format.html { render :edit }
        format.json { render json: @miniature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miniatures/1
  # DELETE /miniatures/1.json
  def destroy
    @miniature.destroy
    respond_to do |format|
      format.html { redirect_to miniatures_url, notice: 'Miniature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def by_user_for_game
    @game = Game.find(params[:game])
    @miniatures = Miniature.where("game_id = ? AND user_id = ?", params[:game], current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_miniature
      @miniature = Miniature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def miniature_params
      params.require(:miniature).permit(:name, :count, :description)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/miniatures_helper.rb
module MiniaturesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'button' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/dashboard.html.erb
<div class="row">
  <div class="large-6 columns">
    <h2>My Collection</h2>
    <ul>
      <% for game in @games %>
      <li>
        <a href="/collection/<%= game.id %>"><%= game.name %></a>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<h1>War Collector</h1>

<p>
  Keep track of your miniatures. Never say "do I actually have that?" again.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>War Collector</title>
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/normalize.min.css">
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.min.css">
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/js/vendor/jquery.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/js/foundation.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <% if user_signed_in? %>
        <h1><a href="/dashboard">War Collector</a></h1>
        <% else %>
        <h1><a href="/">War Collector</a></h1>
        <% end %>
      </li>
    </ul>
    <section class="top-bar-section">
      <% if user_signed_in? %>
        <ul class="right">
          <li>
            <%= link_to 'Log Out', destroy_user_session_path %>
          </li>
        </ul>
        <ul class="left">
          <li>
            <%= link_to 'Games', games_path %>
          </li>
          <li>
            <%= link_to 'Miniatures', miniatures_path %>
          </li>
        </ul>
      <% else %>
        <ul class="right">
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Register', new_user_registration_path %></li>
        </ul>
      <% end %>
    </section>
  </nav>
  <div class="row">
      <div class="large-12 columns">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/miniatures/_form.html.erb
<%= form_for(@miniature) do |f| %>
  <% if @miniature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@miniature.errors.count, "error") %> prohibited this miniature from being saved:</h2>

      <ul>
      <% @miniature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :game %><br>
    <%= f.collection_select(:game, Game.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'button' %>
  </div>
<% end %>

app/views/miniatures/by_user_for_game.html.erb
<h2>My <%= @game.name %> Collection</h2>

<ul>
  <% for miniature in @miniatures %>
  <li>
    <a href="/miniatures/<%= miniature.id %>"><%= miniature.name %>: <%= miniature.count %></a>
  </li>
  <% end %>
</ul>

app/views/miniatures/edit.html.erb
<h1>Editing Miniature</h1>

<%= render 'form' %>

<%= link_to 'Show', @miniature %> |
<%= link_to 'Back', miniatures_path %>

app/views/miniatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Miniatures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @miniatures.each do |miniature| %>
      <tr>
        <td><%= miniature.name %></td>
        <td><%= miniature.count %></td>
        <td><%= miniature.description %></td>
        <td><%= link_to 'Show', miniature %></td>
        <td><%= link_to 'Edit', edit_miniature_path(miniature) %></td>
        <td><%= link_to 'Destroy', miniature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Miniature', new_miniature_path %>

app/views/miniatures/new.html.erb
<h1>New Miniature</h1>

<%= render 'form' %>

<%= link_to 'Back', miniatures_path %>

app/views/miniatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @miniature.name %>
</p>

<p>
  <strong>Count:</strong>
  <%= @miniature.count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @miniature.description %>
</p>

<%= link_to 'Edit', edit_miniature_path(@miniature) %> |
<%= link_to 'Back', miniatures_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'button' %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>